### ISSUE TITLE
Remove bin and obj directories

### ISSUE THREAD

**Issue by amaitland** [sentialx/WebExpress#1]
Hi @Sential 

I'd suggest you remove the `bin` and `obj` directories from your repository, much easier to do whilst there's only a handful of commits. Also add a `.gitignore` file so they don't get re-added.

**Comment by sentialx** [comment]
Ok :D

**Comment by amaitland** [comment]
If it helps you can use https://github.com/amaitland/WebExpress-beta and force push, I merged all commits together, then excluded the `bin` and `obj` folders, added a `.gitignore` then did a `force push` over the top :smile:

**Comment by sentialx** [comment]
Thank you for help! I will also add `.gitignore` to my github. :smile:

**Comment by Sential** [comment]
I added `.gitignore` to my project but this isn't work.

**Comment by amaitland** [comment]
I see you added the `,gitignore` and removed the folders :+1: 

They're still part of your commit history unfortunately, so a fresh `clone` if your `repository` will still have to download about `70mb` more than is necessary. Just making you aware :smile: 

Closing this now.

**Comment by amaitland** [comment]
```
Cloning into 'F:\projects\WebExpress-beta'...
POST git-upload-pack (200 bytes)
remote: Counting objects: 478, done.
remote: Compressing objects: 100% (321/321), done.
Receiving objects: 100% (478/478), 148.14 MiB | 380.00 KiB/s, done.
Resolving deltas: 100% (214/214), done.
remote: Total 478 (delta 214), reused 389 (delta 125), pack-reused 0
Checking connectivity... done.
```

Was almost `150mb` to perform a fresh `clone` of your repository, not ideal :frowning:

**Comment by sentialx** [comment]
Oh, how can I minimize this?

**Comment by amaitland** [comment]
The official reference is http://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery#Removing-Objects

If you don't care about your commit history then there is an easier method.
