### ISSUE TITLE
Dispatcher.BeginInvoke

### ISSUE THREAD

**Issue by amaitland** [sentialx/WebExpress#2]
Hi @Sential 

I had a few minutes so went over some of your code in a little more detail, I'm a little conserned that you may have taken my advice about when to use `Dispatcher.BeginInvoke` and applies it to other areas of your code where it may not be relevant.

using it from the `CefSharp` handlers and events is perfect like https://github.com/Sential/WebExpress-beta/blob/b2a26990e2fca5b6976dfad627ec3bf2efa41b77/WebExpress/Applets/TabView.xaml.cs#L137

Using it in cases like `LoadSuggestions` isn't idea, you spawn a new task, only to immediately switch back to running on the `UI` thread. So the `WPF` events, like `Loaded` will already be on the correct thread.

https://github.com/Sential/WebExpress-beta/blob/b2a26990e2fca5b6976dfad627ec3bf2efa41b77/WebExpress/Applets/TabView.xaml.cs#L357

Another couple of instances where you shouldn't need to use `BeginInvoke`
https://github.com/Sential/WebExpress-beta/blob/master/WebExpress/Tabs/Tab.xaml.cs#L51
https://github.com/Sential/WebExpress-beta/blob/master/WebExpress/Tabs/Tab.xaml.cs#L71

**Comment by amaitland** [comment]
I don't have a huge amount of spare time at the moment, happy to help out a little bit if I have time :smile:

**Comment by amaitland** [comment]
Also look at something like https://www.stevefenton.co.uk/2012/09/wpf-bubbling-a-command-from-a-child-view/

Methods that need to be called in the `MainWindow` can often be raised in the child, then bubble up :+1:

**Comment by sentialx** [comment]
Oh sorry for Begininvoke, I'm learning about multithreading ;) I'm not so good at invoking, multithreading and other :/

**Comment by sentialx** [comment]
You can contribute with me :smile:

**Comment by amaitland** [comment]
I'll help where I can :smile: 

If your unsure, add a `Dispatcher.CheckAccess()` call, this will help you identify if your already on the `UI` thread. It will return true if you already are.

https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L903

Next step I think is to reduce some of the code duplication, just consolidate things a bit so you get a sense of what's actually required.

**Comment by amaitland** [comment]
When you get a spare minute maybe have a look at the `CefSharp.Wpf.Example` project (obviously copy anything from there you find useful).

https://github.com/cefsharp/CefSharp/tree/master/CefSharp.Wpf.Example

It's a little rough around the edges, fairly solid though. Hasn't had all the polish I'd like to see applied to a commercial application. 

Do you have any experience with using `MVVM`?

**Comment by sentialx** [comment]
Ok. I haven't any experience with mvvm :/ I know what is it.
